#pragma once

#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <deque>
#include <iostream>
#include <cstdint>
#include <sstream>
#include <fstream>
#include <filesystem>
#include <glm/glm.hpp>
#include <SDL2/SDL.h>
#include <glad/glad.h>
#include <stb/stb_image.h>
#include <spdlog/spdlog.h>
#include <algorithm>
#include <utility>
#include <mutex>